services:
  runner:
    build: .
    image: youssefbrr/github-actions:latest # You can use this image or build your own
    group_add:
      - "988"
    restart: always
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock